#!/usr/bin/env python3
"""
API Contract Generator (v3.1)
Part of Dasafo Factory Architecture Department.

Automates the creation and validation of OpenAPI/DTO contracts to enforce 
strict decoupling between Backend and Frontend.
"""

import json
import yaml
import argparse
import sys
import os

def create_base_openapi(title, version, description):
    """Generates a skeleton OpenAPI 3.0.0 structure."""
    return {
        "openapi": "3.0.0",
        "info": {
            "title": title,
            "version": version,
            "description": description
        },
        "paths": {
            "/health": {
                "get": {
                    "summary": "Health Check",
                    "responses": {
                        "200": {
                            "description": "System is operational",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "status": {"type": "string"},
                                            "version": {"type": "string"}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {
            "schemas": {}
        }
    }

def validate_standards(contract_path):
    """Checks if the OpenAPI contract adheres to Dasafo Industrial Standards."""
    try:
        with open(contract_path, 'r') as f:
            if contract_path.endswith('.json'):
                spec = json.load(f)
            else:
                spec = yaml.safe_load(f)
    except Exception as e:
        return False, f"Error reading file: {str(e)}"

    errors = []
    # 1. Check for /health endpoint
    if "/health" not in spec.get("paths", {}):
        errors.append("Missing mandatory '/health' endpoint.")

    # 2. Check for versioning
    if "info" not in spec or "version" not in spec["info"]:
        errors.append("Missing API version in info section.")

    if errors:
        return False, " | ".join(errors)
    return True, "API Contract adheres to Industrial Standards."

def main():
    parser = argparse.ArgumentParser(description="Dasafo API Architect Tool")
    parser.add_argument("--action", choices=["generate", "validate"], required=True)
    parser.add_argument("--output", help="Output path for the generated contract")
    parser.add_argument("--input", help="Input path for validation or base config")
    parser.add_argument("--title", default="Dasafo Project API", help="API Title")
    parser.add_argument("--version", default="0.1.0", help="API Version")

    args = parser.parse_args()

    if args.action == "generate":
        if not args.output:
            print("ERROR: --output is required for generation.")
            sys.exit(1)
        
        spec = create_base_openapi(args.title, args.version, "Auto-generated by Dasafo Architect.")
        
        with open(args.output, 'w') as f:
            if args.output.endswith('.json'):
                json.dump(spec, f, indent=2)
            else:
                yaml.dump(spec, f, sort_keys=False)
        print(f"✅ API Contract generated at {args.output}")

    elif args.action == "validate":
        if not args.input:
            print("ERROR: --input is required for validation.")
            sys.exit(1)
        
        success, message = validate_standards(args.input)
        if success:
            print(f"✅ {message}")
        else:
            print(f"❌ ARCHITECTURAL FAILURE: {message}")
            sys.exit(1)

if __name__ == "__main__":
    main()
