"""
run.py — API Contract Generator (ARCHITECT)
v3.1.5: Solidity Guard | Industrial Scale.

Automates the creation and validation of OpenAPI/DTO contracts.
"""

from __future__ import annotations
import sys
import json
import yaml
import os
from pathlib import Path

# Add factory knowledge to path
sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "00_GLOBAL_KNOWLEDGE"))
from skill_schema import SkillInput, SkillOutput

def create_base_openapi(title: str, version: str, description: str) -> dict:
    """Generates a skeleton OpenAPI 3.0.0 structure."""
    return {
        "openapi": "3.0.0",
        "info": {
            "title": title,
            "version": version,
            "description": description
        },
        "paths": {
            "/health": {
                "get": {
                    "summary": "Health Check",
                    "responses": {
                        "200": {
                            "description": "System is operational",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "status": {"type": "string"},
                                            "version": {"type": "string"}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {
            "schemas": {}
        }
    }

def run(skill_input: SkillInput) -> SkillOutput:
    """Standardized entry point for the skill."""
    action = skill_input.params.get("action", "generate")
    title = skill_input.params.get("title", "Dasafo Project API")
    api_version = skill_input.params.get("version", "0.1.0")
    
    target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
    artifact_paths = []

    if action == "generate":
        spec = create_base_openapi(title, api_version, "Auto-generated by Dasafo Architect v3.1.5.")
        
        if target:
            output_path = Path(target) / "DOCS" / "API-CONTRACT.yaml"
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                yaml.dump(spec, f, sort_keys=False)
            artifact_paths.append(str(output_path))
            
            return SkillOutput.success(
                agent=skill_input.agent,
                skill=skill_input.skill,
                data={"message": f"API Contract generated at {output_path}"},
                artifacts=artifact_paths,
                correlation_id=skill_input.correlation_id
            )
        else:
             return SkillOutput.success(
                agent=skill_input.agent,
                skill=skill_input.skill,
                data={"spec": spec},
                correlation_id=skill_input.correlation_id
            )

    return SkillOutput.failure(
        agent=skill_input.agent,
        skill=skill_input.skill,
        error=f"Unsupported action: {action}",
        correlation_id=skill_input.correlation_id
    )
