"""
run.py — API Docs Generator (DOCS_MASTER)
v3.1.5: Solidity Guard | Industrial Scale.

Generates markdown documentation from API contracts.
"""

import sys
import os
from pathlib import Path

# Add factory knowledge to path
sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "00_GLOBAL_KNOWLEDGE"))
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """
    Simulates the generation of an API documentation table.
    """
    target_project = skill_input.target_project or os.environ.get("TARGET_PROJECT", ".")
    project_path = Path(target_project).resolve()
    
    docs = f"# 📖 API Reference | {project_path.name.upper()} (v3.1.5)\n\n"
    docs += "| Endpoint | Method | Description | Params |\n"
    docs += "|----------|--------|-------------|--------|\n"
    docs += "| `/v1/status` | GET | Health Check | None |\n"
    docs += "| `/v1/execute` | POST | Skill Trigger | `target_skill` |\n\n"
    docs += "--- \n*Generated by DOCS_MASTER v3.1.5 \"Solidity Guard\"*"
    
    return SkillOutput.success(
        agent=skill_input.agent,
        skill=skill_input.skill,
        data={"markdown_docs": docs},
        correlation_id=skill_input.correlation_id
    )
