"""
run.py — API Docs Generator (DOCS_MASTER)
Generates markdown documentation from API contracts.
v2.1: Project-agnostic path resolution.
"""

import os
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """
    Simulates the generation of an API documentation table.
    """
    target_project = skill_input.target_project or os.environ.get("TARGET_PROJECT", ".")
    project_path = Path(target_project).resolve()
    
    docs = f"# 📖 API Reference | {project_path.name.upper()}\n\n"
    docs += "| Endpoint | Method | Description | Params |\n"
    docs += "|----------|--------|-------------|--------|\n"
    docs += "| `/v1/status` | GET | Health Check | None |\n"
    docs += "| `/v1/execute` | POST | Skill Trigger | `target_skill` |\n\n"
    docs += "--- \n*Generated by DOCS_MASTER v2.1*"
    
    return SkillOutput.success(
        agent=skill_input.agent,
        skill=skill_input.skill,
        data={"markdown_docs": docs},
        correlation_id=skill_input.correlation_id
    )
