import os
import json
import time
from pathlib import Path

# Logic based on: https://skills.sh/wshobson/agents/design-system-patterns

def get_base_tokens() -> dict:
    """Provides base primitive tokens for the design system."""
    return {
        "primitive": {
            "color-blue-500": "#3b82f6",
            "color-blue-600": "#2563eb",
            "color-gray-900": "#171717",
            "color-gray-50": "#fafafa",
            "space-1": "0.25rem",
            "space-4": "1rem",
            "radius-md": "0.5rem"
        },
        "semantic": {
            "text-primary": "var(--color-gray-900)",
            "surface-default": "var(--color-gray-50)",
            "interactive-primary": "var(--color-blue-500)"
        },
        "component": {
            "button-bg": "var(--interactive-primary)",
            "button-radius": "var(--radius-md)"
        }
    }

def generate_css(tokens: dict) -> str:
    """Generates CSS custom properties from the token hierarchy."""
    css = "/* Design Tokens v5.0-MCP | Generated by DS Pattern Engine */\n\n:root {\n"
    for layer in ["primitive", "semantic", "component"]:
        css += f"  /* {layer.capitalize()} Layer */\n"
        for k, v in tokens.get(layer, {}).items():
            css += f"  --{k}: {v};\n"
        css += "\n"
    css += "}\n\n/* Industrial SI Compliance: Unit rem/s enforced. */\n"
    return css

def execute_atomic_tokens(
    target_project: str,
    action: str = "init",
    layer: str = "primitive",
    name: str = None,
    value: str = None,
    overwrite: bool = False
) -> tuple[dict, list]:
    """Pure logic for UI Atomic Design synchronization (v5.0-MCP)."""
    start_time = time.time()
    project_path = Path(target_project).resolve()
    styles_dir = project_path / "ui" / "styles"
    styles_dir.mkdir(parents=True, exist_ok=True)
    
    token_store = styles_dir / "design_tokens.json"
    css_path = styles_dir / "tokens.css"
    
    # Load or Init
    if token_store.exists():
        with open(token_store, 'r', encoding='utf-8') as f:
            tokens = json.load(f)
    else:
        tokens = get_base_tokens()

    industrial_status = "SYSTEM_INITIALIZED"

    if action == "add_token":
        if not name or not value:
            raise ValueError("Missing 'name' or 'value' for add_token action.")
        layer = layer.lower()
        if layer not in tokens: tokens[layer] = {}
        tokens[layer][name] = value
        industrial_status = "TOKEN_LINKED"
    
    elif action == "generate":
        industrial_status = "STYLE_GENERATED"

    # DAST Persistence
    if css_path.exists() and not overwrite and action == "init":
        raise FileExistsError(f"REDUNDANCY LOCK: {css_path.name} already exists.")

    with open(token_store, 'w', encoding='utf-8') as f:
        json.dump(tokens, f, indent=2, ensure_ascii=False)

    css_content = generate_css(tokens)
    css_path.write_text(css_content, encoding="utf-8")

    result = {
        "industrial_status": industrial_status,
        "artifacts": [str(token_store), str(css_path)],
        "hierarchy_report": {
            "primitive_count": len(tokens.get("primitive", {})),
            "semantic_count": len(tokens.get("semantic", {}))
        },
        "execution_duration_seconds": round(time.time() - start_time, 4)
    }
    
    return result, [str(token_store), str(css_path)]