from __future__ import annotations
import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — Atomic Design Tokens & DS Patterns (FRONTEND_DEV / UI_ARCHITECT)
v3.3.0-S: Modular Toolbox | Industrial Scale.

Advanced module to manage three-tier design tokens (Primitive, Semantic, Component).
Based on wshobson/agents/design-system-patterns logic.
"""

import os
import json
import re
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def get_base_tokens() -> dict:
    """Provides starting primitives for the design system."""
    return {
        "primitive": {
            "color-blue-500": "#3b82f6",
            "color-blue-600": "#2563eb",
            "color-gray-900": "#171717",
            "color-gray-50": "#fafafa",
            "space-1": "0.25rem",
            "space-4": "1rem",
            "radius-md": "0.5rem"
        },
        "semantic": {
            "text-primary": "var(--color-gray-900)",
            "surface-default": "var(--color-gray-50)",
            "interactive-primary": "var(--color-blue-500)"
        },
        "component": {
            "button-bg": "var(--interactive-primary)",
            "button-radius": "var(--radius-md)"
        }
    }

def generate_css(tokens: dict) -> str:
    """Generates CSS Custom Properties from the token hierarchy."""
    css = "/* Design Tokens v3.3.0-S | Generated by DS Pattern Engine */\n\n:root {\n"
    
    # Primitives
    css += "  /* Primitives */\n"
    for k, v in tokens.get("primitive", {}).items():
        css += f"  --{k}: {v};\n"
    
    # Semantics
    css += "\n  /* Semantics */\n"
    for k, v in tokens.get("semantic", {}).items():
        css += f"  --{k}: {v};\n"
        
    # Components
    css += "\n  /* Components */\n"
    for k, v in tokens.get("component", {}).items():
        css += f"  --{k}: {v};\n"
        
    css += "}\n\n"
    css += "/* Industrial SI Compliance: Unit rem/s enforced. */\n"
    return css

def run(skill_input: SkillInput) -> SkillOutput:
    """Industrial Entry Point for UI Atomic Design."""
    agent = skill_input.agent or "FRONTEND_DEV"
    skill = "atomic-design-tokens"
    cid = skill_input.correlation_id
    params = skill_input.params or {}

    try:
        # 1. Path & Context Resolution
        target = params.get("target_project") or skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
             return SkillOutput.failure(agent, skill, "SECURITY LOCK: Missing TARGET_PROJECT path.", cid)
        
        project_path = Path(target).resolve()
        styles_dir = project_path / "ui" / "styles"
        styles_dir.mkdir(parents=True, exist_ok=True)
        
        token_store = styles_dir / "design_tokens.json"
        action = params.get("action", "init")

        # 2. Logic: Load Token Store
        if token_store.exists():
             with open(token_store, 'r', encoding='utf-8') as f:
                  tokens = json.load(f)
        else:
             tokens = get_base_tokens()

        # 3. Handle Actions
        if action == "add_token":
             layer = params.get("layer", "primitive").lower()
             name = params.get("name")
             value = params.get("value")
             if not name or not value:
                  return SkillOutput.failure(agent, skill, "INPUT_ERROR: Missing 'name' or 'value'.", cid)
             
             if layer not in tokens:
                  tokens[layer] = {}
             tokens[layer][name] = value

        # 4. Persistence
        with open(token_store, 'w', encoding='utf-8') as f:
             json.dump(tokens, f, indent=2)

        css_content = generate_css(tokens)
        css_path = styles_dir / "tokens.css"
        css_path.write_text(css_content, encoding="utf-8")

        # 5. Result Building
        result_payload = {
            "status": "SYSTEM_INITIALIZED" if action == "init" else "STYLE_GENERATED",
            "artifacts": [str(token_store), str(css_path)],
            "hierarchy_report": {
                "primitive_count": len(tokens.get("primitive", {})),
                "semantic_count": len(tokens.get("semantic", {})),
                "component_count": len(tokens.get("component", {}))
            },
            "si_alignment": True
        }

        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result=result_payload,
            artifacts=[str(token_store), str(css_path)],
            correlation_id=cid
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"CRITICAL UI Pattern Fault: {str(e)}", cid)
