"""
skill_schema.py — Unified data contract for all dasafo_FACTORY Skills.

All run.py scripts MUST import SkillInput and SkillOutput from this module.
This ensures an explicit, typed contract between the execution engine and each skill.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


@dataclass
class SkillInput:
    """
    Standard input payload for any executable skill.

    Attributes:
        agent:       ID of the agent invoking the skill (e.g., 'orchestrator').
        skill:       Name of the skill (e.g., 'ra-agile-orchestration').
        params:      Skill-specific parameter dictionary.
        target_project: Absolute path to the active project. If None, read from $TARGET_PROJECT.
        correlation_id: Traceability ID for distributed logging.
    """
    agent: str
    skill: str
    params: Dict[str, Any] = field(default_factory=dict)
    target_project: Optional[str] = None
    correlation_id: Optional[str] = None

    @classmethod
    def from_json(cls, raw: str) -> "SkillInput":
        data = json.loads(raw)
        return cls(
            agent=data["agent"],
            skill=data["skill"],
            params=data.get("params", {}),
            target_project=data.get("target_project"),
            correlation_id=data.get("correlation_id"),
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class SkillOutput:
    """
    Standard result returned by any executable skill.

    Attributes:
        success:     True if the skill completed without critical errors.
        agent:       ID of the agent that executed the skill.
        skill:       Name of the skill executed.
        result:      Output payload (varies by skill).
        artifacts:   List of file paths generated by the skill.
        warnings:    Non-blocking warnings encountered during execution.
        error:       Error message if success=False.
        correlation_id: Traceability ID inherited from SkillInput.
    """
    success: bool
    agent: str
    skill: str
    result: Dict[str, Any] = field(default_factory=dict)
    artifacts: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    error: Optional[str] = None
    correlation_id: Optional[str] = None

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(asdict(self), indent=indent, ensure_ascii=False)

    @classmethod
    def failure(
        cls,
        agent: str,
        skill: str,
        error: str,
        correlation_id: Optional[str] = None,
    ) -> "SkillOutput":
        """Factory to build an error result concisely."""
        return cls(
            success=False,
            agent=agent,
            skill=skill,
            error=error,
            correlation_id=correlation_id,
        )
