"""
run.py — Skill: Search Context Distillation Pro
Agent: MEMORY_OPTIMIZER

Comprime un log de conversación/contexto largo en un resumen mínimo vital.
Output: MEMORY_SNAPSHOT.md en el TARGET_PROJECT.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "00_GLOBAL_KNOWLEDGE"))
from skill_schema import SkillInput, SkillOutput  # noqa: E402

_SNAPSHOT_TEMPLATE = """# 🧠 Memory Snapshot

> **Source:** {source_label}  
> **Compressed:** {date}  
> **Original length:** {original_chars} chars → **Snapshot:** {snapshot_chars} chars  
> **Compression ratio:** {compression_ratio}%

---

## Key Decisions

{key_decisions}

## Open Tasks

{open_tasks}

## Critical Context

{critical_context}

## Entities Mentioned

{entities}

---
*Generated by MEMORY_OPTIMIZER — search-context-distillation-pro skill*
"""


def _extract_sections(text: str) -> dict:
    """
    Extracción heurística de secciones clave del contexto.
    En producción, esta función sería reemplazada por una llamada a un LLM de compresión.
    """
    lines = text.splitlines()
    decisions: list[str] = []
    tasks: list[str] = []
    entities: set[str] = set()

    for line in lines:
        stripped = line.strip()
        # Decisiones: líneas que contienen palabras clave de decisión
        if any(kw in stripped.lower() for kw in ["decided", "decision", "chosen", "approved", "agreed", "decidido", "aprobado"]):
            decisions.append(f"- {stripped[:200]}")

        # Tareas: líneas con marcadores de tarea
        if any(kw in stripped for kw in ["[ ]", "[x]", "[/]", "TODO", "PENDING", "IN PROGRESS"]):
            tasks.append(f"- {stripped[:200]}")

        # Entidades: palabras en MAYÚSCULAS (nombres de agentes, sistemas)
        import re
        caps_words = re.findall(r"\b[A-Z][A-Z_]{2,}\b", stripped)
        entities.update(caps_words[:5])  # máx 5 por línea para no explotar

    return {
        "key_decisions": "\n".join(decisions[:10]) or "- [Ninguna decisión explícita detectada]",
        "open_tasks": "\n".join(tasks[:15]) or "- [Ninguna tarea pendiente detectada]",
        "entities": ", ".join(sorted(entities)) or "N/A",
    }


def run(skill_input: SkillInput) -> SkillOutput:
    agent = skill_input.agent
    skill = skill_input.skill
    cid = skill_input.correlation_id

    content = skill_input.params.get("content")
    source_label = skill_input.params.get("source_label", "Conversación sin etiquetar")
    critical_context = skill_input.params.get("critical_context", "[Proveer manualmente en 'critical_context' param]")

    if not content:
        # Intenta leer de un archivo si se provee ruta
        source_file = skill_input.params.get("source_file")
        if source_file and Path(source_file).exists():
            content = Path(source_file).read_text(encoding="utf-8", errors="ignore")
            source_label = source_label or Path(source_file).name
        else:
            return SkillOutput.failure(
                agent, skill,
                "Se requiere 'content' (texto) o 'source_file' (ruta a archivo) en params.",
                cid,
            )

    sections = _extract_sections(content)
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    original_chars = len(content)

    snapshot_text = _SNAPSHOT_TEMPLATE.format(
        source_label=source_label,
        date=date,
        original_chars=original_chars,
        snapshot_chars=0,  # placeholder, calculado abajo
        compression_ratio=0,  # placeholder
        critical_context=critical_context,
        **sections,
    )

    snapshot_chars = len(snapshot_text)
    compression_ratio = round((1 - snapshot_chars / max(original_chars, 1)) * 100, 1)

    # Reconstruir con valores reales
    snapshot_text = _SNAPSHOT_TEMPLATE.format(
        source_label=source_label,
        date=date,
        original_chars=original_chars,
        snapshot_chars=snapshot_chars,
        compression_ratio=compression_ratio,
        critical_context=critical_context,
        **sections,
    )

    artifacts: list[str] = []
    warnings: list[str] = []

    target_project = skill_input.target_project
    if target_project:
        snapshot_path = Path(target_project) / "MEMORY_SNAPSHOT.md"
        snapshot_path.parent.mkdir(parents=True, exist_ok=True)
        snapshot_path.write_text(snapshot_text, encoding="utf-8")
        artifacts.append(str(snapshot_path))
    else:
        warnings.append("TARGET_PROJECT no definido. El snapshot no fue persistido en disco.")

    return SkillOutput(
        success=True,
        agent=agent,
        skill=skill,
        result={
            "original_chars": original_chars,
            "snapshot_chars": snapshot_chars,
            "compression_ratio": f"{compression_ratio}%",
            "sections_extracted": list(sections.keys()),
        },
        artifacts=artifacts,
        warnings=warnings,
        correlation_id=cid,
    )
