from __future__ import annotations
import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — API Contract Generator (ARCHITECT)
v3.2.0-S: Modular Toolbox | Industrial Scale.

Automates the creation and validation of OpenAPI/DTO contracts.
"""

import yaml
import os
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def create_base_openapi(title: str, version: str, description: str) -> dict:
    """Generates a skeleton OpenAPI 3.0.0 structure."""
    return {
        "openapi": "3.0.0",
        "info": {
            "title": title,
            "version": version,
            "description": description
        },
        "paths": {
            "/health": {
                "get": {
                    "summary": "Health Check",
                    "responses": {
                        "200": {
                            "description": "System is operational",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "status": {"type": "string"},
                                            "version": {"type": "string"}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {
            "schemas": {}
        }
    }

def run(skill_input: SkillInput) -> SkillOutput:
    """Standardized entry point for the skill."""
    # Dinamicidad v3.2.0-S: Usar los valores del input para trazabilidad
    agent = skill_input.agent or "ARCHITECT"
    skill = skill_input.skill or "api-contract-generator"
    cid = skill_input.correlation_id

    try:
        # 1. Input Resolution
        params = skill_input.params
        action = params.get("action", "generate")
        title = params.get("title", "Dasafo Project API")
        api_version = params.get("version", "0.1.0")
        
        target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
        
        if not target and action == "generate":
             return SkillOutput.failure(agent, skill, "Mission Blocked: TARGET_PROJECT is missing.", cid)

        spec = create_base_openapi(title, api_version, "Auto-generated by Dasafo Architect v3.2.0-S.")

        if action == "generate":
            project_path = Path(target).resolve()
            # Aseguramos que DOCS exista según el contrato de la skill
            output_dir = project_path / "DOCS"
            output_dir.mkdir(parents=True, exist_ok=True)
            
            output_path = output_dir / "API-CONTRACT.yaml"
            
            with open(output_path, 'w', encoding='utf-8') as f:
                yaml.dump(spec, f, sort_keys=False)
            
            return SkillOutput.success(
                agent=agent,
                skill=skill,
                result={
                    "message": f"Industrial Contract generated successfully.",
                    "path": str(output_path)
                },
                correlation_id=cid,
                artifacts=[str(output_path)] # Vital para Solidity Guard
            )
        else:
             return SkillOutput.success(
                agent=agent,
                skill=skill,
                result={"spec": spec},
                correlation_id=cid,
                artifacts=[]
            )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"Critical Contract Failure: {str(e)}", cid)