import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — API Docs Generator (ARCHITECT)
v3.2.0-S: Modular Toolbox | Industrial Scale.

Generates markdown documentation from API contracts.
"""

import os
import yaml
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """Industrialized entry point: Physical YAML Parsing."""
    agent = "ARCHITECT"
    skill = "api-docs-generator"
    cid = skill_input.correlation_id

    try:
        # 1. Resolution
        target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
            return SkillOutput.failure(agent, skill, "Missing TARGET_PROJECT", cid)
        
        project_path = Path(target).resolve()
        input_name = skill_input.params.get("input_name", "API-CONTRACT.yaml")
        input_path = project_path / "DOCS" / input_name
        
        if not input_path.exists():
            return SkillOutput.failure(agent, skill, f"Contract not found: {input_path}", cid)

        # 2. Logic: Real Parsing
        with open(input_path, 'r', encoding='utf-8') as f:
            spec = yaml.safe_load(f)

        title = spec.get("info", {}).get("title", "API Reference")
        version = spec.get("info", {}).get("version", "1.0.0")

        docs_content = f"# 📖 API Reference | {title} (v{version})\n\n"
        docs_content += "| Endpoint | Method | Description |\n"
        docs_content += "|----------|--------|-------------|\n"
        
        paths = spec.get("paths", {})
        for path, methods in paths.items():
            for method, details in methods.items():
                summary = details.get("summary", "No description")
                docs_content += f"| `{path}` | {method.upper()} | {summary} |\n"
                
        docs_content += "\n--- \n*Generated by ARCHITECT v3.2.4-S \"Modular Toolbox\" (Physically Parsed)*\n"

        # 3. Persistence
        output_name = skill_input.params.get("output_name", "API_REFERENCE.md")
        output_path = project_path / "DOCS" / output_name
        output_path.write_text(docs_content, encoding="utf-8")

        # 4. Return
        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result={
                "markdown_docs": docs_content,
                "endpoints_found": len(paths),
                "path": str(output_path),
                "industrial_verification": True
            },
            correlation_id=cid,
            artifacts=[str(output_path)]
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"Doc generation failed: {str(e)}", cid)
