from __future__ import annotations
import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — API Documentation Generator (ARCHITECT / DOCS_MASTER)
v3.4.0-S: Modular Toolbox | Industrial Scale.

Transform an OpenAPI contract (YAML) into a complete and beautiful Markdown documentation.
Based on sickn33/antigravity-awesome-skills/api-documentation-generator logic.
"""

import os
import yaml
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def generate_code_examples(method: str, path: str, title: str) -> str:
    """Generates basic code snippets for the endpoint."""
    url = f"https://api.example.com{path}"
    
    curl = f"```bash\ncurl -X {method.upper()} \"{url}\" \\\n     -H \"Authorization: Bearer <TOKEN>\" \\\n     -H \"Content-Type: application/json\"\n```"
    
    python = f"```python\nimport requests\n\nurl = \"{url}\"\nheaders = {{\"Authorization\": \"Bearer <TOKEN>\", \"Content-Type\": \"application/json\"}}\nresponse = requests.{method.lower()}(url, headers=headers)\nprint(response.json())\n```"
    
    ts = f"```typescript\nimport axios from 'axios';\n\nconst url = '{url}';\nconst headers = {{ 'Authorization': `Bearer ${{token}}`, 'Content-Type': 'application/json' }};\nconst {{ data }} = await axios.{method.lower()}(url, {{ headers }});\nconsole.log(data);\n```"
    
    return f"#### Examples\n\n**cURL:**\n{curl}\n\n**Python:**\n{python}\n\n**TypeScript:**\n{ts}\n"

def get_pro_docs(spec: dict, include_examples: bool = True) -> str:
    """Generates professional Markdown documentation from the OpenAPI spec."""
    info = spec.get("info", {})
    title = info.get("title", "Industrial API Reference")
    version = info.get("version", "1.0.0")
    desc = info.get("description", "Comprehensive API documentation generated by Dasafo Architect (v3.4.0-S).")

    md = f"# 📖 {title} (v{version})\n\n"
    md += f"{desc}\n\n"
    
    # 🗝️ Getting Started Section
    md += "## 🚀 Getting Started\n\n"
    md += "### 🔐 Authentication\n\n"
    md += "All requests to the API must include a `Bearer token` in the `Authorization` header:\n\n"
    md += "```\nAuthorization: Bearer <YOUR_JWT_TOKEN>\n```\n\n"
    md += "### ⚡ Rate Limits & Performance\n\n"
    md += "To ensure stability, the API uses rate limiting. Responses will include the following headers:\n"
    md += "- `X-RateLimit-Limit`: Maximum requests per minute.\n"
    md += "- `X-RateLimit-Remaining`: Remaining requests in the current window.\n\n"

    # 📡 Endpoints Section
    md += "## 📡 Endpoints\n\n"
    
    paths = spec.get("paths", {})
    for path, methods in paths.items():
        for method, details in methods.items():
            md += f"### `{method.upper()}` {path}\n\n"
            md += f"**Summary:** {details.get('summary', 'No summary')}\n\n"
            if "description" in details:
                md += f"**Description:** {details['description']}\n\n"
            
            # 📜 Parameters
            params = details.get("parameters", [])
            if params:
                md += "| Parameter | In | Type | Required | Description |\n"
                md += "|-----------|----|------|----------|-------------|\n"
                for p in params:
                    name = p.get("name", "N/A")
                    p_in = p.get("in", "query")
                    p_type = p.get("schema", {}).get("type", "string")
                    req = "Yes" if p.get("required") else "No"
                    p_desc = p.get("description", "")
                    md += f"| `{name}` | {p_in} | `{p_type}` | {req} | {p_desc} |\n"
                md += "\n"

            # 📦 Request Body
            req_body = details.get("requestBody", {})
            if req_body:
                md += "**Request Body:**\n\n"
                md += f"- **Content:** `application/json`\n"
                # (Simplified schema parsing here, but extensible for Pydantic/Zod DTOs)
                md += f"- **Required:** {'Yes' if req_body.get('required') else 'No'}\n\n"

            # 💹 Responses
            md += "**Responses:**\n\n"
            md += "| Code | Description | Content |\n"
            md += "|------|-------------|---------|\n"
            for code, resp in details.get("responses", {}).items():
                content_type = list(resp.get("content", {}).keys())[0] if resp.get("content") else "N/A"
                md += f"| `{code}` | {resp.get('description', '')} | `{content_type}` |\n"
            md += "\n"

            # 🛠️ Code Examples
            if include_examples:
                md += generate_code_examples(method, path, title)
            
            md += "\n---\n\n"

    # 📐 SI Units Disclosure
    md += "## 📐 Industrial Compliance (Sistema Internacional)\n\n"
    md += "De acuerdo con el mandato **v3.4.0-S**, todas las métricas operativas de esta API se expresan bajo el **Sistema Internacional d'Unitats (SI)**:\n"
    md += "- **Tiempos de respuesta y timeouts:** Expresados estrictamente en **segundos (s)**.\n"
    md += "- **Límites de carga (Payload):** Expresados en **bytes (B)** o **kilobytes (KB)**.\n"
    md += "- **Cuotas de peticiones:** Frecuencias expresadas en **hercios (Hz)** o peticiones por segundo.\n"
    
    md += "\n\n*Generated by Agentic Documentation Engine (v3.4.0-S) | Source: sickn33/api-documentation-generator*"
    return md

def run(skill_input: SkillInput) -> SkillOutput:
    """Industrial entry point for professional documentation."""
    agent = "ARCHITECT"
    skill = "api-docs-generator"
    cid = skill_input.correlation_id
    params = skill_input.params or {}

    try:
        # 1. Path & Context Resolution
        target = params.get("target_project") or skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
             return SkillOutput.failure(agent, skill, "SECURITY LOCK: Missing TARGET_PROJECT path.", cid)
        
        project_path = Path(target).resolve()
        input_name = params.get("contract_path", "API-CONTRACT.yaml")
        input_path = project_path / "DOCS" / input_name
        
        if not input_path.exists():
            return SkillOutput.failure(agent, skill, f"PHYSICAL_ERROR: Source contract {input_path} not found.", cid)

        # 2. Logic: Real Parsing (Solid Ground)
        with open(input_path, 'r', encoding='utf-8') as f:
            spec = yaml.safe_load(f)

        # 3. Doc Generation (Professional Grade)
        include_examples = params.get("include_examples", True)
        docs_content = get_pro_docs(spec, include_examples)

        # 4. Persistence
        output_name = params.get("output_name", "API_REFERENCE_PRO.md")
        output_path = project_path / "DOCS" / output_name
        output_path.write_text(docs_content, encoding="utf-8")

        # 5. Result Building
        endpoints_count = sum(len(methods) for methods in spec.get("paths", {}).values())
        
        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result={
                "markdown_docs": docs_content[:500] + "...", # Truncate in console
                "path": str(output_path),
                "endpoints_documented": endpoints_count,
                "industrial_status": "SOLIDIFIED - PRO DOCS GENERATED"
            },
            correlation_id=cid,
            artifacts=[str(output_path)]
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"CRITICAL Doc generation failed: {str(e)}", cid)
