"""
run.py — API Docs Generator (ARCHITECT)
v3.2.0-S: Modular Toolbox | Industrial Scale.

Generates markdown documentation from API contracts.
"""

from __future__ import annotations
import os
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """Standardized entry point for the skill."""
    agent = "ARCHITECT"
    skill = "api-docs-generator"
    cid = skill_input.correlation_id

    try:
        # 1. Resolution
        target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
            return SkillOutput.failure(agent, skill, "Missing TARGET_PROJECT", cid)
        
        project_path = Path(target).resolve()
        output_name = skill_input.params.get("output_name", "API_REFERENCE.md")
        output_path = project_path / "DOCS" / output_name
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # 2. Logic (Mock/Simple Generation for now)
        docs_content = f"# 📖 API Reference | {project_path.name.upper()} (v3.2.0-S)\n\n"
        docs_content += "| Endpoint | Method | Description | Params |\n"
        docs_content += "|----------|--------|-------------|--------|\n"
        docs_content += "| `/v1/status` | GET | Health Check | None |\n"
        docs_content += "| `/v1/execute` | POST | Skill Trigger | `target_skill` |\n\n"
        docs_content += "--- \n*Generated by ARCHITECT v3.2.0-S \"Modular Toolbox\"*"

        # 3. Persistence
        output_path.write_text(docs_content, encoding="utf-8")

        # 4. Return
        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result={
                "markdown_docs": docs_content,
                "path": str(output_path)
            },
            correlation_id=cid,
            artifacts=[str(output_path)]
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"Error: {str(e)}", cid)
