import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — Design Token Definition (ARCHITECT / FRONTEND_DEV)
v3.3.0-S: Modular Toolbox | Industrial Scale.

Defines and validates the visual identity tokens for premium industrial UI.
"""

from __future__ import annotations
import os
import json
import time
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

# v3.3.0-S Premium Industrial Tokens
DEFAULT_TOKENS = {
    "version": "3.3.0-S",
    "theme": "Stark-Dark",
    "colors": {
        "brand": "#A855F7",    # Premium Purple
        "accent": "#06B6D4",   # Cyber Cyan
        "danger": "#EF4444",   # Industrial Red
        "success": "#22C55E",  # Matrix Green
        "background": "#0F172A",
        "surface": "rgba(30, 41, 59, 0.7)", # Glass Surface
        "glass": "rgba(255, 255, 255, 0.03)"
    },
    "effects": {
        "blur": "16px",
        "border": "1px solid rgba(255, 255, 255, 0.1)",
        "shadow": "0 8px 32px 0 rgba(0, 0, 0, 0.8)",
        "transition": "400ms cubic-bezier(0.23, 1, 0.32, 1)"
    },
    "typography": {
        "headings": "Outfit, sans-serif",
        "body": "Inter, sans-serif",
        "mono": "JetBrains Mono, monospace"
    },
    "spacing": { "unit": 4, "base": 16, "scale": "1.5" }
}

def run(skill_input: SkillInput) -> SkillOutput:
    """Industrialized entry point for token definition."""
    agent = skill_input.agent or "ARCHITECT"
    skill = "design-token-definition"
    cid = skill_input.correlation_id

    try:
        # 1. Path Resolution
        target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
            return SkillOutput.failure(agent, skill, "Missing TARGET_PROJECT context.", cid)
        
        project_path = Path(target).resolve()
        action = skill_input.params.get("action", "validate")

        token_path = project_path / "LOCAL_KNOWLEDGE" / "architecture" / "design-tokens.json"
        doc_path = project_path / "DOCS" / "Visual_Standard.md"
        artifacts = []

        # 2. Logic (Export/Sync)
        if action == "export":
            token_path.parent.mkdir(parents=True, exist_ok=True)
            with open(token_path, "w", encoding="utf-8") as f:
                json.dump(DEFAULT_TOKENS, f, indent=2)
            artifacts.append(str(token_path))

            # Generate/Update Visual Standard
            doc_path.parent.mkdir(parents=True, exist_ok=True)
            timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
            doc_content = f"""# 🎨 Visual Standard (v3.3.0-S)

> **Last Updated:** {timestamp}
> **Authority:** {agent}

## 💎 Design Tokens (JSON)
The physical truth is located in: `LOCAL_KNOWLEDGE/architecture/design-tokens.json`

## 🧱 Typography
- **Headings:** {DEFAULT_TOKENS['typography']['headings']}
- **Body:** {DEFAULT_TOKENS['typography']['body']}
- **Mono:** {DEFAULT_TOKENS['typography']['mono']}

## ✨ Effects
- **Glassmorphism:** Blur {DEFAULT_TOKENS['effects']['blur']} | Border {DEFAULT_TOKENS['effects']['border']}
- **Transition:** {DEFAULT_TOKENS['effects']['transition']}

---
*Generated by Dasafo Factory | Solidity Guard v3.3.0-S*
"""
            doc_path.write_text(doc_content, encoding="utf-8")
            artifacts.append(str(doc_path))

        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result={
                "tokens": DEFAULT_TOKENS,
                "token_path": str(token_path),
                "doc_path": str(doc_path),
                "status": "PREMIUM_STARK"
            },
            correlation_id=cid,
            artifacts=artifacts
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"Token Fault: {str(e)}", cid)
