"""
run.py — ADR Generator (ARCHITECT)
Generates Architectural Decision Records (ADR) in the project workspace.
v3.1: Infraestructura Blindada | Industrial Scale.
"""

import os
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """
    Creates an ADR file in the target project.
    """
    target_project = skill_input.target_project or os.environ.get("TARGET_PROJECT", ".")
    project_path = Path(target_project).resolve()
    
    adr_title = skill_input.params.get("title", "Unknown Decision")
    adr_id = skill_input.params.get("id", "0001")
    context = skill_input.params.get("context", "No context provided.")
    decision = skill_input.params.get("decision", "No decision documented.")
    
    adr_content = f"# ADR-{adr_id}: {adr_title}\n\n"
    adr_content += f"## Context\n{context}\n\n"
    adr_content += f"## Decision\n{decision}\n\n"
    adr_content += f"## Status\nACCEPTED\n\n"
    adr_content += f"---\n*Generated by ARCHITECT | Unified Factory v2.1*"
    
    # Save to project
    doc_path = project_path / "DOCS" / "ADR"
    doc_path.mkdir(parents=True, exist_ok=True)
    
    file_path = doc_path / f"ADR-{adr_id}-{adr_title.lower().replace(' ', '-')}.md"
    file_path.write_text(adr_content, encoding="utf-8")
    
    return SkillOutput.success(
        agent=skill_input.agent,
        skill=skill_input.skill,
        data={"path": str(file_path)},
        correlation_id=skill_input.correlation_id
    )
