"""
run.py — Skill: Architecture Decision Records (ADR)
Agent: ARCHITECT

Genera un ADR con la plantilla estándar (Contexto, Decisión, Consecuencias)
y lo escribe en $TARGET_PROJECT/ARCHITECTURE_DECISION_RECORD.md.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "00_GLOBAL_KNOWLEDGE"))
from skill_schema import SkillInput, SkillOutput  # noqa: E402

_ADR_TEMPLATE = """# ADR-{adr_id:04d}: {title}

> **Date:** {date}  
> **Status:** {status}  
> **Architect:** {architect}

---

## Context

{context}

## Decision

{decision}

## Consequences

### Positive
{positive_consequences}

### Negative / Trade-offs
{negative_consequences}

### Risks
{risks}

---
*ADR generated by ARCHITECT — architecture-decision-records skill*
"""


def _next_adr_id(adr_file: Path) -> int:
    """Cuenta los ADRs existentes en el archivo para asignar el siguiente ID."""
    if not adr_file.exists():
        return 1
    content = adr_file.read_text(encoding="utf-8")
    # Cuenta ocurrencias de "# ADR-" en el archivo
    return content.count("# ADR-") + 1


def run(skill_input: SkillInput) -> SkillOutput:
    agent = skill_input.agent
    skill = skill_input.skill
    cid = skill_input.correlation_id

    title = skill_input.params.get("title")
    context = skill_input.params.get("context", "")
    decision = skill_input.params.get("decision", "")
    positive = skill_input.params.get("positive_consequences", "- [Pendiente de documentar]")
    negative = skill_input.params.get("negative_consequences", "- [Pendiente de documentar]")
    risks = skill_input.params.get("risks", "- [Pendiente de documentar]")
    status = skill_input.params.get("status", "Proposed")
    architect = skill_input.params.get("architect", "ARCHITECT agent")

    if not title:
        return SkillOutput.failure(agent, skill, "Param 'title' es requerido.", cid)
    if not context:
        return SkillOutput.failure(agent, skill, "Param 'context' es requerido.", cid)
    if not decision:
        return SkillOutput.failure(agent, skill, "Param 'decision' es requerido.", cid)

    target_project = skill_input.target_project
    if not target_project:
        return SkillOutput.failure(
            agent, skill,
            "TARGET_PROJECT no definido. El ADR requiere una ruta de proyecto para ser persistido.",
            cid,
        )

    adr_file = Path(target_project) / "ARCHITECTURE_DECISION_RECORD.md"
    adr_id = _next_adr_id(adr_file)
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    adr_content = _ADR_TEMPLATE.format(
        adr_id=adr_id,
        title=title,
        date=date,
        status=status,
        architect=architect,
        context=context,
        decision=decision,
        positive_consequences=positive,
        negative_consequences=negative,
        risks=risks,
    )

    # Append al archivo (no sobreescribe ADRs anteriores)
    adr_file.parent.mkdir(parents=True, exist_ok=True)
    with adr_file.open("a", encoding="utf-8") as f:
        f.write("\n" + adr_content if adr_file.exists() else adr_content)

    return SkillOutput(
        success=True,
        agent=agent,
        skill=skill,
        result={
            "adr_id": adr_id,
            "title": title,
            "status": status,
            "date": date,
        },
        artifacts=[str(adr_file)],
        correlation_id=cid,
    )
