#!/bin/bash

# ==============================================================================
# dasafo_FACTORY | Project Initializer (Bootstrap) v5.0-MCP (SDD Optimized)
# ==============================================================================
# This script provisions the strict $TARGET_PROJECT skeleton mandated by the 
# 00_CORE_CONSTITUTION.md (Spec Driven Development & Clean Sessions).
#
# Usage: ./init_project.sh <PROJECT_NAME>
# ==============================================================================

set -e

if [ -z "$1" ]; then
    echo "ERROR: Target project name is required."
    echo "Usage: ./init_project.sh <PROJECT_NAME>"
    exit 1
fi

PROJECT_ROOT="../PROJECTS/$1"

echo "[*] Initializing SDD factory skeleton for project: $1"

# 1. Create CORE skeleton architecture (v5.0-MCP Chasis Blindado)
mkdir -p "$PROJECT_ROOT/DOCS/ARCH"
mkdir -p "$PROJECT_ROOT/DOCS/USER"
mkdir -p "$PROJECT_ROOT/LOGS/agents"
mkdir -p "$PROJECT_ROOT/LOGS/sessions"
mkdir -p "$PROJECT_ROOT/TASKS/01_PENDING"
mkdir -p "$PROJECT_ROOT/TASKS/02_IN_PROGRESS"
mkdir -p "$PROJECT_ROOT/TASKS/03_COMPLETED"
mkdir -p "$PROJECT_ROOT/WORKSPACE/backend"
mkdir -p "$PROJECT_ROOT/WORKSPACE/frontend"
mkdir -p "$PROJECT_ROOT/WORKSPACE/shared"

# 2. Create Industrial Task List (task.md) - Visual Mirror
cat <<EOF > "$PROJECT_ROOT/TASKS/task.md"
# 📝 SDD Kanban | $1
> **Standard:** v5.0-MCP (Clean Sessions Enabled)
> **Status:** Phase M1 (Discovery)

## Phase M1: Discovery (IN_PROGRESS)
- [ ] PRODUCT_OWNER: Generate PRP_MASTER using \`prp-generator\`.

## Phase M2: Architecture (PENDING)
- [ ] ORCHESTRATOR: Deconstruct PRP_MASTER into SPEC_LITE tasks.
- [ ] ARCHITECT: Define DTOs and Layer Boundaries in DOCS/ARCH/.

## Phase M3: Production (PENDING)
- [ ] PEONS (FRONT/BACK): Execute Clean Sessions via \`delegate_clean_session\`.
- [ ] No-Code Persistence: All specs met and verified on disk.

## Phase M4: Compliance (PENDING)
- [ ] QA_TESTER: Cultural Linter audit (Chasis Blindado check).
- [ ] Solidity Gate: kanban-solidity-gate VERIFIED.

## Phase M5: Operations (PENDING)
- [ ] MEMORY_OPTIMIZER: Engram sorting and Feedback Log extraction.

---
*Generated by dasafo_FACTORY v5.0-MCP*
EOF

# 3. Create Industrial Task Registry (registry.json) - Single Source of Truth
cat <<EOF > "$PROJECT_ROOT/TASKS/registry.json"
[
  {
    "id": "M1-001",
    "title": "Generate PRP_MASTER Contract via prp-generator",
    "status": "IN_PROGRESS",
    "phase": "M1",
    "metadata": {
        "assigned_agent": "PRODUCT_OWNER"
    },
    "dependencies": []
  }
]
EOF

# 4. Physical Kanban Seeding (v5.0-MCP Physical Sync Mandate)
cat <<EOF > "$PROJECT_ROOT/TASKS/02_IN_PROGRESS/SPEC_LITE.json"
{
  "id": "M1-001",
  "title": "Generate PRP_MASTER Contract via prp-generator",
  "status": "IN_PROGRESS",
  "phase": "M1",
  "metadata": {
    "assigned_agent": "PRODUCT_OWNER",
    "production_category": "DEFINE"
  },
  "dependencies": []
}
EOF

# 5. Create Project State (Aduana Universal)
cat <<EOF > "$PROJECT_ROOT/PROJECT_STATE.json"
{
  "factory_version": "5.0-MCP",
  "project_status": "DISCOVERY",
  "current_phase": "M1",
  "objective": "Formulate project vision and sign PRP_MASTER contract.",
  "phases": {
    "M1": "IN_PROGRESS",
    "M2": "PENDING",
    "M3": "PENDING",
    "M4": "PENDING",
    "M5": "PENDING"
  }
}
EOF

# 6. Seed the PRP_CONTRACT (Directo a Raíz según Mandato v5.0-MCP)
cat <<EOF > "$PROJECT_ROOT/PRP_CONTRACT.json"
{
  "project": "$1",
  "factory_standard": "v5.0-MCP",
  "prp_status": "AWAITING_GENERATION"
}
EOF

# 7. Seed Engram / Feedback Log
cat <<EOF > "$PROJECT_ROOT/LOGS/FEEDBACK-LOG.md"
# 🧠 Engram Substrate | $1
> **Standard:** v5.0-MCP (SDD Optimized)
> **Notice:** Do not write raw text here. Use FEEDBACK_SCHEMA.json payloads.

---
*Memory Status: Pristine.*
EOF

# 8. Corregir sintaxis del .env e inyectar Infraestructura de Memoria
echo "DOCKER_NETWORK=dasafo_network" > "$PROJECT_ROOT/.env"
echo "SUPABASE_PROJECT_URL=https://[PROJECT_ID].supabase.co" >> "$PROJECT_ROOT/.env"
echo "SUPABASE_SERVICE_ROLE_KEY=[HIDDEN]" >> "$PROJECT_ROOT/.env"
echo "REDIS_HOST=localhost" >> "$PROJECT_ROOT/.env"
echo "REDIS_PORT=6379" >> "$PROJECT_ROOT/.env"

# 9. Local Privacy & Solidification
cat <<EOF > "$PROJECT_ROOT/.gitignore"
LOGS/agents/*
LOGS/sessions/*
.env
__pycache__/
*.pyc
EOF

# 10. Provisionar Hoja de Firma Humana
cp "../dasafo_FACTORY/00_GLOBAL_KNOWLEDGE/TEMPLATES/approval.md" "$PROJECT_ROOT/DOCS/USER/APPROVAL_M1.md"


# ==============================================================================
# 🛡️ 11. INYECCIÓN DE GUARDIAN ANGEL HOOKS (AUDIT MODE v5.1)
# ==============================================================================
echo "[*] Injecting Aggressive Guardian Angel DAST Hooks..."

mkdir -p "$PROJECT_ROOT/.githooks"

# Python Guardian Engine (Full Audit Logic)
cat <<'EOF' > "$PROJECT_ROOT/.githooks/guardian.py"
import os, sys, importlib.util
from pathlib import Path

# Rutas de la Factoría
PROJECT_ROOT = Path(os.getcwd())
FACTORY_ROOT = PROJECT_ROOT.parent.parent / "dasafo_FACTORY"

if not FACTORY_ROOT.exists():
    print("⚠️ [GUARDIAN ANGEL] Factory Core no encontrado. Saltando Aduana.")
    sys.exit(0)

def load_skill(name, path_dir):
    """Carga una skill de la factoría de forma aislada para evitar colisiones."""
    spec = importlib.util.spec_from_file_location(name, path_dir / "logic.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

print("🛡️ Ejecutando Aduana Universal (Full Audit Mode)...")
has_failed = False

# 1. SECRET SCANNER ENFORCEMENT
try:
    scanner_path = FACTORY_ROOT / "06_SKILL_LIBRARY" / "agentic-thought-secret-scanner"
    secret_logic = load_skill("secret_logic", scanner_path)
    res, _ = secret_logic.execute_scan(str(PROJECT_ROOT))
    if res.get("secrets_found", 0) > 0:
        print(f"\n🚨 [GUARDIAN FATAL] BLOQUEO DE SEGURIDAD: {res['secrets_found']} secretos.")
        for f in res.get("findings", []):
            print(f"   ✖ {f['file']}:{f['line']} -> {f['type']}")
        has_failed = True
except Exception as e:
    print(f"⚠️ [GUARDIAN WARNING] Scanner falló: {e}")

# 2. BACKBONE VALIDATOR ENFORCEMENT
try:
    backbone_path = FACTORY_ROOT / "06_SKILL_LIBRARY" / "project-backbone-validator"
    backbone_logic = load_skill("backbone_logic", backbone_path)
    
    # Validar Backend si existe
    if (PROJECT_ROOT / "WORKSPACE" / "backend").exists() and any((PROJECT_ROOT / "WORKSPACE" / "backend").iterdir()):
        res, _ = backbone_logic.execute_backbone_validation(str(PROJECT_ROOT), "fastapi")
        if not res.get("scaffolding_ready", False):
            print(f"\n🚨 [GUARDIAN FATAL] BLOQUEO ESTRUCTURAL: Backend incompleto.")
            print(f"   ✖ Faltan: {res.get('missing_bones')}")
            has_failed = True
            
    # Validar Frontend si existe
    if (PROJECT_ROOT / "WORKSPACE" / "frontend").exists() and any((PROJECT_ROOT / "WORKSPACE" / "frontend").iterdir()):
        res, _ = backbone_logic.execute_backbone_validation(str(PROJECT_ROOT), "nextjs")
        if not res.get("scaffolding_ready", False):
            print(f"\n🚨 [GUARDIAN FATAL] BLOQUEO ESTRUCTURAL: Frontend incompleto.")
            print(f"   ✖ Faltan: {res.get('missing_bones')}")
            has_failed = True
except Exception as e:
    print(f"⚠️ [GUARDIAN WARNING] Backbone validator falló: {e}")

if has_failed:
    print("\n❌ COMMIT ABORTADO POR LA ADUANA UNIVERSAL.")
    sys.exit(1)

print("✅ [GUARDIAN ANGEL] Solidificación aprobada. Commit autorizado.")
sys.exit(0)
EOF

# Bash Pre-commit Trigger
cat <<'EOF' > "$PROJECT_ROOT/.githooks/pre-commit"
#!/bin/bash
python3 .githooks/guardian.py
EOF

# Script de instalación
cat <<'EOF' > "$PROJECT_ROOT/setup_git_hooks.sh"
#!/bin/bash
git config core.hooksPath .githooks
echo "✅ Git hooks configurados. El Guardian Angel está activo en tu IDE."
EOF

chmod +x "$PROJECT_ROOT/.githooks/pre-commit"
chmod +x "$PROJECT_ROOT/setup_git_hooks.sh"

echo "[+] SUCCESS: Factory ready for Phase M1 (Discovery)."


# ==============================================================================
echo "[+] Directory structure created dynamically at: $PROJECT_ROOT"
echo "[+] Standardized under 00_CORE_CONSTITUTION.md."
echo "[+] Master Registry seeded for Clean Sessions."
echo "[+] Aduana Universal state initialized to v5.0-MCP."
echo "[+] Guardian Angel Hooks generados en .githooks/"
echo "[+] SUCCESS: Factory ready for Phase M1 (Discovery)."