#!/bin/bash

# ==============================================================================
# dasafo_FACTORY | Project Initializer (Bootstrap) v3.4.0-S (SDD Optimized)
# ==============================================================================
# This script provisions the strict $TARGET_PROJECT skeleton mandated by the 
# 00_CORE_CONSTITUTION.md (Spec Driven Development & Clean Sessions).
#
# Usage: ./init_project.sh <PROJECT_NAME>
# ==============================================================================

set -e

if [ -z "$1" ]; then
    echo "ERROR: Target project name is required."
    echo "Usage: ./init_project.sh <PROJECT_NAME>"
    exit 1
fi

PROJECT_ROOT="../../PROJECTS/$1"

echo "[*] Initializing SDD factory skeleton for project: $1"

# 1. Create CORE skeleton architecture (v3.4.0-S Chasis Blindado)
mkdir -p "$PROJECT_ROOT/DOCS/ARCH"
mkdir -p "$PROJECT_ROOT/DOCS/USER"
mkdir -p "$PROJECT_ROOT/LOGS/agents"
mkdir -p "$PROJECT_ROOT/LOGS/sessions"
mkdir -p "$PROJECT_ROOT/TASKS/01_PENDING"
mkdir -p "$PROJECT_ROOT/TASKS/02_IN_PROGRESS"
mkdir -p "$PROJECT_ROOT/TASKS/03_COMPLETED"
mkdir -p "$PROJECT_ROOT/WORKSPACE/backend"
mkdir -p "$PROJECT_ROOT/WORKSPACE/frontend"
mkdir -p "$PROJECT_ROOT/WORKSPACE/shared"

# 2. Create Industrial Task List (task.md) - Visual Mirror
cat <<EOF > "$PROJECT_ROOT/TASKS/task.md"
# 📝 SDD Kanban | $1
> **Standard:** v3.4.0-S (Clean Sessions Enabled)
> **Status:** Phase M1 (Discovery)

## Phase M1: Discovery (IN_PROGRESS)
- [ ] PRODUCT_OWNER: Generate PRP_MASTER using \`prp-generator\`.

## Phase M2: Architecture (PENDING)
- [ ] ORCHESTRATOR: Deconstruct PRP_MASTER into SPEC_LITE tasks.
- [ ] ARCHITECT: Define DTOs and Layer Boundaries in DOCS/ARCH/.

## Phase M3: Production (PENDING)
- [ ] PEONS (FRONT/BACK): Execute Clean Sessions via \`delegate_clean_session\`.
- [ ] No-Code Persistence: All specs met and verified on disk.

## Phase M4: Compliance (PENDING)
- [ ] QA_TESTER: Cultural Linter audit (Chasis Blindado check).
- [ ] Solidity Gate: kanban-solidity-gate VERIFIED.

## Phase M5: Operations (PENDING)
- [ ] MEMORY_OPTIMIZER: Engram sorting and Feedback Log extraction.

---
*Generated by dasafo_FACTORY v3.4.0-S*
EOF

# 3. Create Industrial Task Registry (registry.json) - Single Source of Truth
cat <<EOF > "$PROJECT_ROOT/TASKS/registry.json"
[
  {
    "id": "M1-001",
    "title": "Generate PRP_MASTER Contract via prp-generator",
    "status": "PENDING",
    "phase": "M1",
    "assigned_to": "PRODUCT_OWNER",
    "dependencies": []
  }
]
EOF

# 4. Physical Kanban Seeding (v3.4.0-S Physical Sync Mandate)
cat <<EOF > "$PROJECT_ROOT/TASKS/01_PENDING/M1-001.json"
{
  "id": "M1-001",
  "title": "Generate PRP_MASTER Contract via prp-generator",
  "status": "PENDING",
  "phase": "M1",
  "assigned_to": "PRODUCT_OWNER",
  "dependencies": []
}
EOF

# 5. Create Project State (Aduana Universal)
cat <<EOF > "$PROJECT_ROOT/PROJECT_STATE.json"
{
  "factory_version": "3.4.0-S",
  "project_status": "DISCOVERY",
  "current_phase": "M1",
  "objective": "Formulate project vision and sign PRP_MASTER contract.",
  "phases": {
    "M1": "PENDING",
    "M2": "PENDING",
    "M3": "PENDING",
    "M4": "PENDING",
    "M5": "PENDING"
  }
}
EOF

# 6. Seed the PRP_CONTRACT (Placeholder for Generator)
cat <<EOF > "$PROJECT_ROOT/DOCS/ARCH/PRP_CONTRACT.json"
{
  "project": "$1",
  "factory_standard": "v3.4.0-S",
  "prp_status": "AWAITING_GENERATION",
  "instruction": "PRODUCT_OWNER must use 'prp-generator' skill (Action: GENERATE_MASTER) to overwrite this file."
}
EOF

# 7. Seed Engram / Feedback Log
cat <<EOF > "$PROJECT_ROOT/LOGS/FEEDBACK-LOG.md"
# 🧠 Engram Substrate | $1
> **Standard:** v3.4.0-S (SDD Optimized)
> **Notice:** Do not write raw text here. Use FEEDBACK_SCHEMA.json payloads.

---
*Memory Status: Pristine.*
EOF

# 8. Infrastructure Hint (v3.4.0-S Industrial Core)
echo "DOCKER_NETWORK=dasafo_network" > "$PROJECT_ROOT/.env"
echo "SUPABASE_PROJECT_URL=https://[PROJECT_ID].supabase.co" >> "$PROJECT_ROOT/.env"
echo "SUPABASE_SERVICE_ROLE_KEY=[HIDDEN]" >> "$PROJECT_ROLE_KEY=[HIDDEN]" >> "$PROJECT_ROOT/.env"

# 9. Local Privacy & Solidification
cat <<EOF > "$PROJECT_ROOT/.gitignore"
LOGS/agents/*
LOGS/sessions/*
.env
__pycache__/
*.pyc
EOF

echo "[+] Directory structure created dynamically at: $PROJECT_ROOT"
echo "[+] Standardized under 00_CORE_CONSTITUTION.md."
echo "[+] Master Registry seeded for Clean Sessions."
echo "[+] Aduana Universal state initialized to v3.4.0-S."
echo "[+] SUCCESS: Factory ready for Phase M1 (Discovery)."
