import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — Architectural Decision Records (ADR)
v3.3.0-S: Modular Toolbox | Industrial Scale.

Generates formal Architectural Decision Records (ADR) for system and database choices.
"""

from __future__ import annotations
import os
import json
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """Industrialized entry point for ADR synthesis."""
    agent = skill_input.agent or "ARCHITECT"
    skill = "architecture-decision-records"
    cid = skill_input.correlation_id

    try:
        # 1. Zero Trust Path Resolution
        target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
            return SkillOutput.failure(agent, skill, "SECURITY LOCK: Missing TARGET_PROJECT to persist ADR.", cid)
        
        project_path = Path(target).resolve()
        
        # 2. Parameters (Extraction with Defaults)
        p = skill_input.params
        adr_title = p.get("title", "Unknown Decision")
        # Auto-calculate next ID if not provided (Zero-Collission logic)
        adr_dir = project_path / "DOCS" / "ADR"
        adr_dir.mkdir(parents=True, exist_ok=True)
        
        existing_adrs = list(adr_dir.glob("ADR-*.md"))
        next_id = len(existing_adrs) + 1
        adr_id = str(p.get("id", next_id)).zfill(4)
        
        context = p.get("context", "Context not defined by agent.")
        decision = p.get("decision", "Decision pending formalization.")
        alternatives = p.get("alternatives", "No alternatives explored.")
        consequences = p.get("consequences", "Consequences not documented.")
        
        # 3. Content Construction (Stark-Solidity Template)
        adr_content = f"""# ADR-{adr_id}: {adr_title}

## Status
ACCEPTED

## Context
{context}

## Alternatives Considered
{alternatives}

## Decision
{decision}

## Consequences
{consequences}

---
*Generated by {agent} (v3.3.0-S) | Industrial Verification Required.*
"""
        
        # 4. Persistence
        file_name = f"ADR-{adr_id}-{adr_title.lower().replace(' ', '-')}.md"
        file_path = adr_dir / file_name
        
        file_path.write_text(adr_content.strip(), encoding="utf-8")
        
        # 5. Result Synthesis
        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result={
                "adr_id": adr_id,
                "path": str(file_path),
                "status": "ACCEPTED",
                "solidity_check": "Physical ADR persisted on disk"
            },
            correlation_id=cid,
            artifacts=[str(file_path)]
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"ADR Creation Fault: {str(e)}", cid)
