import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — ADR Generator (ARCHITECT)
v3.2.0-S: Modular Toolbox | Industrial Scale.

Generates Architectural Decision Records (ADR) in the project workspace.
"""

from __future__ import annotations
import os
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def run(skill_input: SkillInput) -> SkillOutput:
    """Standardized entry point for the skill."""
    agent = "ARCHITECT"
    skill = "architecture-decision-records"
    cid = skill_input.correlation_id

    try:
        # 1. Path Resolution
        target = skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
            return SkillOutput.failure(agent, skill, "Missing TARGET_PROJECT", cid)
        
        project_path = Path(target).resolve()
        
        # 2. Parameters
        adr_title = skill_input.params.get("title", "Unknown Decision")
        adr_id = str(skill_input.params.get("id", "0001")).zfill(4)
        context = skill_input.params.get("context", "No context provided.")
        decision = skill_input.params.get("decision", "No decision documented.")
        alternatives = skill_input.params.get("alternatives", "Not mentioned.")
        consequences = skill_input.params.get("consequences", "Not mentioned.")
        
        # 3. Content Construction
        adr_content = f"# ADR-{adr_id}: {adr_title}\n\n"
        adr_content += f"## Context\n{context}\n\n"
        adr_content += f"## Alternatives\n{alternatives}\n\n"
        adr_content += f"## Decision\n{decision}\n\n"
        adr_content += f"## Consequences\n{consequences}\n\n"
        adr_content += f"## Status\nACCEPTED\n\n"
        adr_content += f"---\n*Generated by ARCHITECT | Unified Factory v3.2.0-S \"Modular Toolbox\"*"
        
        # 4. Persistence
        doc_path = project_path / "DOCS" / "ADR"
        doc_path.mkdir(parents=True, exist_ok=True)
        
        file_name = f"ADR-{adr_id}-{adr_title.lower().replace(' ', '-')}.md"
        file_path = doc_path / file_name
        
        file_path.write_text(adr_content, encoding="utf-8")
        
        # 5. Return
        return SkillOutput.success(
            agent=agent,
            skill=skill,
            result={
                "path": str(file_path),
                "status": "ACCEPTED"
            },
            correlation_id=cid,
            artifacts=[str(file_path)]
        )

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"ADR Creation Failed: {str(e)}", cid)
