from __future__ import annotations
import sys, os; sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
"""
run.py — Architecture Decision Records (ARCHITECT / LEAD_DEV)
v3.3.0-S: Modular Toolbox | Industrial Scale.

Advanced module to manage Architecture Decision Records (ADRs) with sequential IDs and indexing.
Based on wshobson/agents logic.
"""

import os
import re
from datetime import datetime
from pathlib import Path
from skill_schema import SkillInput, SkillOutput

def get_next_id(adr_dir: Path) -> str:
    """Finds the next sequential ID based on existing files."""
    files = list(adr_dir.glob("*.md"))
    ids = []
    for f in files:
        match = re.search(r'^(\d{4})-', f.name)
        if match:
             try:
                  ids.append(int(match.group(1)))
             except ValueError:
                  continue
    
    next_id = max(ids, default=0) + 1
    return f"{next_id:04d}"

def update_index(adr_dir: Path):
    """Refreshes the ADR index (README.md) based on existing files."""
    index_file = adr_dir / "README.md"
    files = sorted(list(adr_dir.glob("*.md")))
    
    md = "# 📝 Architecture Decision Records (ADR)\n\n"
    md += "Formal, immutable log of the project's technical decisions.\n\n"
    md += "## 📜 Index\n\n"
    md += "| ID | Title | Status | Date |\n"
    md += "|----|-------|--------|------|\n"
    
    for f in files:
        if f.name == "README.md" or f.name == "template.md":
            continue
        
        # Parse content for status/title/date
        try:
            content = f.read_text(encoding="utf-8")
        except Exception:
            continue
            
        status_match = re.search(r'\*\*Status:\*\*\s*[\[]*(\w+)', content)
        title_match = re.search(r'# ADR\s*\d{4}\s*\|\s*(.*)', content)
        date_match = re.search(r'\*\*Date:\*\*\s*(.*)', content)
        
        id_str = f.name.split("-")[0]
        status = status_match.group(1) if status_match else "ACCEPTED"
        title = title_match.group(1) if title_match else f.name
        date = date_match.group(1).strip() if date_match else "N/A"
        
        md += f"| [{id_str}]({f.name}) | {title} | {status} | {date} |\n"
        
    md += "\n\n## ⚖️ Mandato SI (v3.3.0-S)\n\n"
    md += "- Todas las latencias registradas deben expresarse en **segundos (s)**.\n"
    md += "- Todas las cuotas de datos deben expresarse en **bytes (B)**.\n"
    md += "\n\n*Generated by Architecture Decision Records Engine (v3.3.0-S)*\n"
    
    index_file.write_text(md, encoding="utf-8")

def run(skill_input: SkillInput) -> SkillOutput:
    """Industrial entry point for ADR recording."""
    agent = skill_input.agent or "ARCHITECT"
    skill = "architecture-decision-records"
    cid = skill_input.correlation_id
    params = skill_input.params or {}

    try:
        # 1. Path & Context Resolution
        target = params.get("target_project") or skill_input.target_project or os.environ.get("TARGET_PROJECT")
        if not target:
             return SkillOutput.failure(agent, skill, "SECURITY LOCK: Missing TARGET_PROJECT path.", cid)
        
        project_path = Path(target).resolve()
        adr_dir = project_path / "DOCS" / "ADR"
        adr_dir.mkdir(parents=True, exist_ok=True)
        
        action = params.get("action", "new")
        
        # 2. Logical Core
        if action == "init":
             update_index(adr_dir)
             return SkillOutput.success(
                 agent=agent,
                 skill=skill,
                 result={"status": "ADR_INITIALIZED"},
                 artifacts=[str(adr_dir / "README.md")],
                 correlation_id=cid
             )

        elif action == "new" or action == "supersede":
             title = params.get("title", "New Architecture Decision")
             context = params.get("context", "Problem and requirements summary.")
             decision = params.get("decision", "The chosen architectural path.")
             consequences = params.get("consequences", "Trade-offs and impact analysis.")
             
             new_id = get_next_id(adr_dir)
             safe_title = re.sub(r'[^\w\s-]', '', title.lower()).replace(' ', '-')
             adr_file = adr_dir / f"{new_id}-{safe_title}.md"
             
             date_str = datetime.now().strftime("%Y-%m-%d")
             status = "ACCEPTED"
             
             # Handle Supersede logic
             supersede_note = ""
             if action == "supersede":
                  old_id = params.get("target_id")
                  if old_id:
                       supersede_note = f"\n**Supersedes:** ADR {old_id}\n"
                       # Attempt to update the status of the OLD ADR
                       old_files = list(adr_dir.glob(f"{old_id}-*.md"))
                       if old_files:
                            try:
                                old_content = old_files[0].read_text(encoding="utf-8")
                                updated_old = old_content.replace("**Status:** ACCEPTED", f"**Status:** SUPERSEDED by {new_id}")
                                old_files[0].write_text(updated_old, encoding="utf-8")
                            except Exception:
                                pass

             adr_md = f"# ADR {new_id} | {title}\n\n"
             adr_md += f"**Date:** {date_str}\n"
             adr_md += f"**Status:** {status}\n"
             adr_md += f"{supersede_note}\n"
             adr_md += f"## 📖 Context\n\n{context}\n\n"
             adr_md += f"## ✅ Decision\n\n{decision}\n\n"
             adr_md += f"## ⚖️ Consequences\n\n{consequences}\n\n"
             adr_md += "---\n\n"
             adr_md += "*ADR Recorded for dasafo_FACTORY v3.3.0-S*\n"

             adr_file.write_text(adr_md, encoding="utf-8")
             update_index(adr_dir)

             return SkillOutput.success(
                 agent=agent,
                 skill=skill,
                 result={
                     "status": "SOLIDIFIED - ADR RECORDED",
                     "adr_path": str(adr_file),
                     "adr_id": new_id,
                     "summary": [f"Decision: {title}", f"Status: {status}"]
                 },
                 artifacts=[str(adr_file), str(adr_dir / "README.md")],
                 correlation_id=cid
             )

        elif action == "list":
             files = sorted(list(adr_dir.glob("*.md")))
             if not files:
                 return SkillOutput.success(agent=agent, skill=skill, result={"status": "EMPTY", "adr_count": 0}, correlation_id=cid)
             
             return SkillOutput.success(
                 agent=agent,
                 skill=skill,
                 result={"status": "FOUND", "adr_count": len(files)-1}, # Exclude index
                 correlation_id=cid
             )

        else:
             return SkillOutput.failure(agent, skill, f"Invalid ADR action: {action}", cid)

    except Exception as e:
        return SkillOutput.failure(agent, skill, f"CRITICAL ADR Fault: {str(e)}", cid)
